kind: Secret
apiVersion: v1
metadata:
  name: supervisor-grafana-credentials
stringData:
  GF_SECURITY_ADMIN_PASSWORD: "Admin!23"
  GF_SECURITY_ADMIN_USER: root
type: Opaque
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: supervisor-grafana
  labels:
    dashboards: supervisor-grafana
spec:
  service:
    spec:
      type: LoadBalancer
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: supervisor-grafana-credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: supervisor-grafana-credentials
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafanadatasource-influxdb-supervisor
spec:
  instanceSelector:
    matchLabels:
      dashboards: supervisor-grafana
  datasource:
    name: InfluxDB
    type: influxdb
    access: proxy
    url: https://vmware-influxdb.demo1.svc.cluster.local
    isDefault: true
    basicAuth: false
    jsonData:
      "defaultBucket": "Supervisor"
      "organization": "VMware"
      "tlsSkipVerify": true
      "version": "Flux"
    secureJsonData:
      token: "{{INFLUXDB API TOKEN}}"
